//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstallerSample.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstallerSample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg936\deff0\deflang1033\deflangfe2052\deftab420{\fonttbl{\f0\fswiss\fprq2\fcharset0 Tahoma;}}
        ///{\*\generator Msftedit 5.41.15.1515;}{\info{\horzdoc}{\*\lchars $([\&apos;7b\&apos;a1\&apos;ea\&apos;a3\&apos;a4\&apos;a1\&apos;a4\&apos;a1\&apos;ae\&apos;a1\&apos;b0\&apos;a1\&apos;b4\&apos;a1\&apos;b6\&apos;a1\&apos;b8\&apos;a1\&apos;ba\&apos;a1\&apos;be\&apos;a1\&apos;b2\&apos;a1\&apos;bc\&apos;a8\&apos;94\&apos;a9\&apos;76\&apos;a9\&apos;78\&apos;a9\&apos;7a\&apos;a1\&apos;e7\&apos;a3\&apos;a8\&apos;a3\&apos;ae\&apos;a3\&apos;db\&apos;a3\&apos;fb\&apos;a1\&apos;ea\&apos;a3\&apos;a4}{\*\fchars !%),.:\&apos;3b&gt;?]\&apos;7d\&apos;a1\&apos;e9\&apos;a1\&apos;a7\&apos;a1\&apos;e3\&apos;a1\&apos;a4\&apos;a1\&apos;a6\&apos;a1\&apos;a5\&apos;a8\&apos;44\&apos;a1\&apos;ac\&apos;a1\&apos;af\&apos;a1\&apos;b1\&apos;a1\&apos;ad\&apos;a1\&apos;eb\&apos;a1\&apos;e4\&apos;a1\&apos;e5?\&apos;a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Apache20 {
            get {
                return ResourceManager.GetString("Apache20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the way you want features to be installed..
        /// </summary>
        internal static string FeaturePageDescription {
            get {
                return ResourceManager.GetString("FeaturePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Selection.
        /// </summary>
        internal static string FeaturePageTitle {
            get {
                return ResourceManager.GetString("FeaturePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Installer Wizard has successfully installed the software. Click Finish to exit the wizard..
        /// </summary>
        internal static string FinishPageDescription {
            get {
                return ResourceManager.GetString("FinishPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer Wizard Completed.
        /// </summary>
        internal static string FinishPageTitle {
            get {
                return ResourceManager.GetString("FinishPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Folder: {0}.
        /// </summary>
        internal static string InstallationFolderPattern {
            get {
                return ResourceManager.GetString("InstallationFolderPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap installer_logo {
            get {
                object obj = ResourceManager.GetObject("installer_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while features are being installed..
        /// </summary>
        internal static string InstallingPageDescription {
            get {
                return ResourceManager.GetString("InstallingPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        internal static string InstallingPageTitle {
            get {
                return ResourceManager.GetString("InstallingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the terms of this agreement to continue. If you do not accept the license terms, click Cancel..
        /// </summary>
        internal static string LicensePageDescription {
            get {
                return ResourceManager.GetString("LicensePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Agreement.
        /// </summary>
        internal static string LicensePageTitle {
            get {
                return ResourceManager.GetString("LicensePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Feature: {0}.
        /// </summary>
        internal static string SelectedFeaturePattern {
            get {
                return ResourceManager.GetString("SelectedFeaturePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review the summary information..
        /// </summary>
        internal static string SummaryPageDescription {
            get {
                return ResourceManager.GetString("SummaryPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string SummaryPageTitle {
            get {
                return ResourceManager.GetString("SummaryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Welcome to the software Installer Wizard&lt;/h1&gt;
        ///    &lt;p&gt;Welcome to the software installer wizard. This wizard will guide you through the steps of installing the software to your computer. Please click Next button to get started.&lt;/p&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string WelcomeHtmlPage {
            get {
                return ResourceManager.GetString("WelcomeHtmlPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the software installer wizard. This wizard will guide you through the steps of installing the software to your computer. Please click Next button to get started..
        /// </summary>
        internal static string WelcomePageDescription {
            get {
                return ResourceManager.GetString("WelcomePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the software Installer Wizard.
        /// </summary>
        internal static string WelcomePageTitle {
            get {
                return ResourceManager.GetString("WelcomePageTitle", resourceCulture);
            }
        }
    }
}
